import json
import os

DICT_DIR = os.path.dirname(os.path.abspath(__file__))
os.makedirs(DICT_DIR, exist_ok=True)

# 1. 職業字典
CLASSES_I18N = {
    "archer": "遊俠 (弓箭手)",
    "knight": "騎士 (聖騎士)",
    "mage": "法師 (元素使)",
    "pet": "戰寵 (靈獸)",
    "priest": "牧師 (神官)",
    "rogue": "刺客 (盜賊)",
    "warrior": "戰士 (狂戰士)"
}

# 2. 稀有度字典
RARITY_I18N = {
    "0.0": "普通 (白)",
    "0": "普通 (白)",
    "1.0": "優秀 (綠)",
    "1": "優秀 (綠)",
    "2.0": "稀有 (藍)",
    "2": "稀有 (藍)",
    "3.0": "史詩 (紫)",
    "3": "史詩 (紫)",
    "4.0": "傳說 (橘)",
    "4": "傳說 (橘)",
    "5.0": "神話 (紅)",
    "5": "神話 (紅)",
    "6.0": "超越/不朽 VII階 (彩紅)",
    "6": "超越/不朽 VII階 (彩紅)"
}

# 3. 種族字典
RACES_I18N = {
    "human": "人類",
    "elf": "精靈",
    "dwarf": "矮人",
    "orc": "獸人",
    "undead": "不死族",
    "demon": "惡魔",
    "dragon": "巨龍族",
    "dragonkin": "龍裔",
    "golem": "魔像",
    "goblin": "哥布林",
    "beast": "野獸",
    "bear": "熊族",
    "bear_monster": "暴走巨熊",
    "wolf": "巨狼族",
    "frogman": "蛙人族",
    "ice_elemental": "冰霜元素",
    "elemental": "元素生物",
    "abomination": "憎惡/縫合怪",
    "voidborn": "虛空後裔",
    "nightshroud": "夜幕幽裔",
    "specter": "幽靈/亡魂",
    "treant": "樹精/樹人",
    "vialkin": "魔藥侏儒",
    "viking": "維京人",
    "breeze_sprite": "微風精靈",
    "tree_sprite": "樹靈",
    "shadow_sprite": "暗影妖精",
    "insect": "昆蟲",
    "fishman": "魚人",
    "skeleton": "骷髏",
    "naga": "娜迦",
    "harpy": "鷹身女妖",
    "slime": "史萊姆"
}

# 4. 傷害類型字典
DAMAGE_TYPE_I18N = {
    "physical": "物理傷害",
    "magic": "魔法傷害",
    "fire": "火焰傷害",
    "ice": "冰霜傷害",
    "holy": "神聖傷害",
    "darkness": "暗影傷害",
    "poison": "毒素傷害",
    "nature": "自然傷害",
    "heal": "治療效果",
    "none": "輔助/被動"
}

# 5. 目標與陣營字典
TARGET_I18N = {
    "party": {
        "enemy": "敵方",
        "ally": "友方",
        "self": "自身",
        "all": "全體"
    },
    "target": {
        "single": "單體",
        "range": "遠程/全範圍",
        "melee": "近戰目標",
        "neighbor": "相鄰目標",
        "dead": "陣亡目標",
        "all": "全體",
        "front_row": "前排",
        "back_row": "後排",
        "lowest_hp": "最低生命值目標",
        "highest_atk": "最高攻擊目標",
        "random": "隨機目標",
        "self": "自身"
    }
}

# 6. 屬性中文翻譯
ATTR_I18N = {
    "hp": "生命值",
    "hp_max": "最大生命值",
    "mp": "魔法值",
    "sp": "能量 (SP)",
    "sp_max": "最大能量值",
    "atk": "攻擊力",
    "matk": "魔法攻擊力",
    "def": "物理防禦",
    "def_mag": "魔法防禦",
    "dam_min": "最小傷害",
    "dam_max": "最大傷害",
    "damage_offset": "傷害係數/倍率",
    "damage_offset_1": "一段傷害倍率",
    "damage_offset_2": "二段傷害倍率",
    "damage_offset_3": "三段傷害倍率",
    "heal_offset": "治療係數/倍率",
    "hp_offset_min": "最小生命回復率",
    "hp_offset_max": "最大生命回復率",
    "shield_hp_offset": "護盾生命係數",
    "crit": "暴擊率 (%)",
    "crit_chance": "暴擊觸發率",
    "crit_res": "暴擊抗性 (%)",
    "crit_damage": "暴擊傷害加成",
    "dodge": "閃避率 (%)",
    "hit_rate": "命中率 (%)",
    "first_strike": "先攻權",
    "physical_con": "物理傷害加深 (%)",
    "physical_res": "物理抗性 (%)",
    "magic_con": "魔法傷害加深 (%)",
    "magic_res": "魔法抗性 (%)",
    "fire_con": "火焰傷害加深 (%)",
    "fire_res": "火焰抗性 (%)",
    "ice_con": "冰霜傷害加深 (%)",
    "ice_res": "冰霜抗性 (%)",
    "holy_con": "神聖傷害加深 (%)",
    "holy_res": "神聖抗性 (%)",
    "darkness_con": "暗影傷害加深 (%)",
    "darkness_res": "暗影抗性 (%)",
    "poison_con": "毒素傷害加深 (%)",
    "poison_res": "毒素抗性 (%)",
    "nature_con": "自然傷害加深 (%)",
    "nature_res": "自然抗性 (%)",
    "heal_con": "治療效果提升 (%)",
    "heal_res": "受到治療提升 (%)",
    "bleed_chance": "流血觸發機率",
    "bleed_max": "流血層數上限",
    "bleed_min": "流血基礎層數",
    "burn_chance": "燃燒觸發機率",
    "burn_max": "燃燒層數上限",
    "burn_min": "燃燒基礎層數",
    "freeze_chance": "凍結觸發機率",
    "freezing_chance": "冰凍觸發機率",
    "frostscar_chance": "霜痕觸發機率",
    "frostscar_max": "霜痕層數上限",
    "frostscar_min": "霜痕基礎層數",
    "frostscar_count": "霜痕附加層數",
    "stun_chance": "眩暈觸發機率",
    "stun_round": "眩暈回合數",
    "poison_chance": "中毒觸發機率",
    "poison_max": "中毒層數上限",
    "poison_min": "中毒基礎層數",
    "weakness_chance": "虛弱觸發機率",
    "weakness_max": "虛弱層數上限",
    "weakness_min": "虛弱基礎層數",
    "mark_chance": "標記觸發機率",
    "mark_count": "標記層數",
    "mark_max": "標記層數上限",
    "mark_min": "標記基礎層數",
    "ap_chance": "獲得行動點機率",
    "ap_count": "獲得行動點數量",
    "energy_chance": "能量獲得機率",
    "energy_charge_count": "充能層數",
    "buff_chance": "增益觸發機率",
    "arrow_count": "箭矢數量",
    "arrow_min": "最小箭矢數",
    "arrow_max": "最大箭矢數",
    "random_count": "隨機連擊次數",
    "shield_offset": "護盾係數",
    "cool_round": "冷卻回合數",
    "create_chance": "生成/召喚機率",
    "remove_chance": "驅散機率",
    "damage_bouns": "額外傷害加成",
    "dam_bouns": "傷害增益",
    "dam_red": "傷害減免",
    "round": "持續回合數",
    "cirt_hp_rate": "斬殺額外暴擊血線閥值",
    "sp_gain": "能量回復"
}

# 7. 英雄專屬名稱字典
HERO_I18N = {
    "hero_mage_ecasia": "寒噬女巫 · 艾卡希雅",
    "hero_archer_theron": "風行神射 · 賽隆",
    "hero_warrior_darok": "碎顱狂戰 · 達羅克",
    "hero_knight_arthur": "聖光誓約 · 亞瑟",
    "hero_priest_eleanor": "晨曦大司祭 · 艾蓮娜",
    "hero_rogue_valen": "夜幕影刃 · 瓦倫"
}

# 8. 技能名稱翻譯字典 (涵蓋官方標準名稱)
SKILL_I18N = {
    # 艾卡希雅專屬與冰系
    "frostscar_spike": "冰痕之刺",
    "shardspire_entombment": "霜棘冰葬",
    "shardspire_cataclysm": "霜棘殞滅",
    "frost_control": "寒冷掌控",
    "icy_soul_echo": "冰魂迴響 (被動)",
    "frostglyph_aegis": "霜紋庇護",
    "icethorn_demise": "冰刺終局 (被動)",

    # 遊俠
    "double_shoot": "雙重射擊",
    "mark_shoot": "印記射擊",
    "scatter_shot": "散射連發",
    "bandage_wounds": "包紮傷口",
    "swift_shot": "迅捷射擊",
    "flow_arrow": "流暢之箭",
    "flowing_arrow": "流光之箭",
    "death_shoot": "致命射擊",
    "cataclysmic_arrow": "滅世天劫箭",
    "multi_mark_shot": "多重標記射擊",
    "dragonbane_arrow": "屠龍穿心箭",
    "frostshot": "冰霜凝結箭",
    "toxic_arrow": "劇毒浸染箭",
    "blade_bow": "刃弓疾斬",
    "guided_twinshot": "導引雙重箭",
    "wingrend_volley": "破翼齊射",
    "anchored_shot": "定錨強射",
    "chaotic_sparkshot": "混沌火花射擊",
    "lightshot": "聖光耀射",
    "marked_hunter": "獵人印記 (被動)",
    "support_fire": "火力支援 (被動)",
    "nightcrow_pierce": "夜鴉穿刺",
    "nightcrow_ascension": "夜鴉飛昇 (被動)",
    "ravenfeather_hunt": "鴉羽追獵",

    # 騎士
    "judgment_spear": "審判之槍",
    "knight_will": "騎士意志",
    "holy_strike": "神聖打擊",
    "defense_blow": "防禦重擊",
    "defensive_strike": "防衛反擊",
    "divine_verdict": "神聖裁決",
    "silver_barrier": "白銀屏障",
    "silver_barrier_slam": "白銀重盾猛擊",
    "holy_light_blessing": "聖光祝福",
    "iron_bastion": "鋼鐵堡壘",
    "holy_spear_charge": "聖槍衝鋒",
    "valiant_charge": "英勇衝鋒",
    "heaven_toll": "天堂鳴鐘",
    "heaven_Judicium": "天堂審判 (被動)",
    "divine_light_spear": "聖光貫穿之槍",
    "divine_revelation_smite": "啟示神罰",
    "knight_sacred_oath": "騎士誓約",
    "oath_blade": "誓約之刃",
    "oathlance_brace": "誓約長槍架勢",
    "oathbound_bulwark": "誓約壁壘",
    "unbroken_vow": "不滅誓言 (被動)",
    "departed_oath": "逝者誓約",
    "protection_wall": "守護之牆",
    "holy_shackles": "聖光桎梏",
    "divine_cycle": "神聖循環 (被動)",

    # 戰士
    "shield_slam": "盾牌猛擊",
    "ironwall_provocation": "鐵壁嘲諷",
    "ironwall_slam": "鐵壁重砸",
    "taunt_skill": "嘲諷怒吼",
    "provoked_fury": "激怒狂暴",
    "mass_provoked_fury": "全體狂怒挑釁",
    "concussion_blast": "震盪爆破",
    "earthquake_slam": "地裂震擊",
    "armor_quake": "碎甲重震",
    "shield_heart": "盾之心 (被動)",
    "shieldbound_cleave": "盾衛順劈",
    "shieldwall_instinct": "盾牆本能 (被動)",
    "shieldwrath_breaker": "盾怒破滅擊",
    "warshield_stance": "戰盾姿態",
    "bloodrage_awakening": "血怒覺醒 (被動)",
    "bloodlust_combo": "嗜血連擊",
    "bloody_blow": "血腥打擊",
    "blood_oath_cleave": "血誓順劈斬",
    "bloodrend_pursuit": "裂血追擊",
    "bloodburst_execution": "爆血處決",
    "blood_recycle": "血液回收 (被動)",
    "flesh_altar": "血肉祭壇",
    "crimson_threshold": "赤紅臨界 (被動)",
    "savage_charge": "野蠻衝撞",
    "savage_overwhelm": "野蠻壓制",
    "unrelenting_fury": "不息怒火 (被動)",
    "burning_rage": "灼熱狂怒",
    "deep_wounds": "深度重傷",
    "bladestorm_quake": "劍刃風暴震盪",
    "trauma_blow": "創傷猛擊",

    # 法師
    "fireball": "火球術",
    "rolling_fireball": "滾動巨炎球",
    "flame_dart": "烈焰飛鏢",
    "blaze_wrath": "熾烈之怒",
    "fire_control": "火焰掌控 (被動)",
    "frostbolt": "寒冰箭",
    "frost_shield": "冰霜護盾",
    "mass_frost_shield": "群體冰霜護盾",
    "glacial_impale": "冰川貫穿",
    "frostquake_resonance": "霜震共鳴",
    "frozen_plating": "極凍裝甲 (被動)",
    "darkness_implosion": "暗影內爆",
    "curse_agony": "痛苦折磨詛咒",
    "mass_curse": "群體詛咒",
    "withering_touch": "枯萎觸碰",
    "touch_void": "虛空之觸",
    "void_fingers": "虛空指引",
    "witherbind": "枯萎束縛",
    "ember_infusion": "餘燼灌注 (被動)",
    "piercing_lightflame": "穿透聖炎",
    "residual_overcharge": "殘餘過載 (被動)",

    # 牧師
    "lesser_heal": "初級治療術",
    "glimmer_heal": "微光治癒",
    "resilient_healing": "韌性復甦術",
    "mass_healing": "群體治療術",
    "blessing_light": "聖光祈福",
    "sanctuary_light": "聖所之光",
    "dark_sanctuary": "暗影庇護所",
    "lightbound_grace": "光縛恩典",
    "light_shield": "聖光護盾",
    "holy_aegis": "神聖聖盾",
    "silver_aegis": "白銀庇護",
    "benediction_fountain": "祝福之泉",
    "radiance_purity": "純淨光輝",
    "sacred_afterglow": "神聖餘暉 (被動)",
    "dawnlight_renewal": "晨光復甦 (被動)",
    "life_source": "生命之源 (被動)",
    "apostolic_revival": "使徒復生 (被動)",
    "ancient_ecclesiarch": "遠古大主教之魂",

    # 刺客
    "sinister_strike": "邪惡攻擊",
    "backstab": "背刺",
    "stealthy_ambush": "潛行伏擊",
    "silent_execution": "無聲處決",
    "deadly_pursuit": "死神追擊",
    "critical_assault": "致命突襲",
    "shadowfang_toss": "影牙投擲",
    "marking_dagger": "標記飛匕",
    "shadowstep_resurgence": "影步復甦 (被動)",
    "shadow_stitching": "暗影縫合",
    "shadow_protection": "暗影守護",
    "shadow_embrace": "暗影擁抱 (被動)",
    "moonshadow_slash": "月影斬",
    "lunar_bladefall": "月刃天降",
    "lunar_judgment": "月之裁決",
    "duskblade_return": "暮刃歸宗 (被動)",
    "twilight_dominion": "暮光支配 (被動)",
    "toxic_strike": "浸毒打擊",
    "toxic_plague": "劇毒瘟疫",
    "poison_control": "毒術掌控 (被動)",
    "venom_recycle": "毒素萃取回收 (被動)",
    "venomous_veil": "毒霧面紗",
    "venomous_wail": "毒液哀嚎",
    "death_omen": "死亡預兆",
    "deathmark_verdict": "死印判決",
    "executioner_edge": "處刑者之刃 (被動)",

    # 戰寵 / 特殊召喚 / 機關 / 深淵
    "thump": "重踏痛擊",
    "brutal_maw": "狂暴巨口撕咬",
    "swift_bite": "迅捷啃咬",
    "rage_claw": "狂怒利爪",
    "rampaging_claws": "暴走狂爪",
    "instinct_ripper": "本能撕裂",
    "great_bear_strength": "巨熊神力 (被動)",
    "restoration_sprite": "復甦妖精",
    "tree_sprite_rebirth": "樹靈重生 (被動)",
    "woodland_aegis": "林地守護",
    "forest_wrath": "森林之怒",
    "root_snare": "纏繞根鬚",
    "thornstorm": "荊棘風暴",
    "nature_control": "自然掌控 (被動)",
    "withered_wood_strike": "枯木猛擊",
    "ancient_resilience": "遠古韌性 (被動)",
    "snowball_toss": "擲雪球",
    "avalanche_charge": "雪崩衝撞",
    "froststeel_charge": "霜鋼衝擊",
    "froststeel_grasp": "霜鋼抓握",
    "froststeel_constitution": "霜鋼體質 (被動)",
    "bone_dart": "白骨飛鏢",
    "bone_guardian": "白骨守衛",
    "wraithbone_shell": "幽魂骨甲",
    "cursed_fang": "詛咒毒牙",
    "shellcurse": "甲殼詛咒",
    "abyss_sunder": "深淵撕裂",
    "abyssal_lunge": "深淵穿刺突進",
    "abyssal_mutation": "深淵異變",
    "abyssal_resonance": "深淵共鳴 (被動)",
    "abysscreep_mutation": "深淵蔓延異變 (被動)",
    "touch_abyss": "深淵之觸",
    "brood_awakening": "巢穴覺醒 (被動)",
    "brooding_cycle": "育卵輪迴",
    "broodmother_command_hero": "母巢之令",
    "soul_rend": "靈魂撕裂",
    "soul_rending_roar": "噬魂咆哮",
    "soulfire_maw": "魂火巨口",
    "draconic_doom_mark": "龍之厄運印記",
    "breath_infusion": "龍息灌注 (被動)",
    "rampage_wings": "狂暴龍翼",
    "scrap_toss": "廢鐵投擲",
    "scrap_toys": "發條機關玩具",
    "scrap_combo": "廢鐵組合連擊",
    "scrapline_reboot": "廢料線重啟 (被動)",
    "gear_cycle_loop": "齒輪循環 (被動)",
    "gearburst_surge": "齒輪爆發增幅",
    "gearfire_barrage": "齒輪彈雨掃射",
    "kinetic_salvage": "動能回收 (被動)",
    "tinker_reboot": "修補重啟 (被動)",
    "fuel_steamroller": "燃料重輾衝撞",
    "deepforge_memory": "深鍛記憶 (被動)",
    "pressurized_taunt": "蒸氣加壓挑釁",
    "self_destruction": "自毀爆炸",
    "out_control_deployment": "失控部屬",
    "dreadlight_echo": "恐懼光芒迴響",
    "shatterline_burst": "碎裂線爆發",
    "sunken_grasp": "沉沒之握",
    "voidwall_conversion": "虛空之牆轉換 (被動)",
    "dimensional_beacon": "維度信標 (被動)",
    "hell_pact_reset": "地獄契約重置 (被動)",
    "helmsman_strike": "掌舵者破浪擊",
    "instant_droplet": "瞬發水滴",
    "tidal_pursuit": "潮汐追襲",
    "gleaming_gift": "閃耀贈禮",
    "martyr_rawness": "殉道之勇 (被動)",
    "scarlet_meditation": "猩紅冥想 (被動)",
    "wild_will": "荒野意志 (被動)",
    "primal_outburst": "原始爆發",
    "quick_preparation": "快速整裝 (被動)",
    "iron_resolve": "鋼鐵堅毅 (被動)",
    "guardian_blow": "守護重擊",
    "mass_defense": "群體防禦祈禱"
}

def save_dicts():
    files = {
        "class_i18n.json": CLASSES_I18N,
        "rarity_i18n.json": RARITY_I18N,
        "race_i18n.json": RACES_I18N,
        "damage_type_i18n.json": DAMAGE_TYPE_I18N,
        "target_i18n.json": TARGET_I18N,
        "attr_i18n.json": ATTR_I18N,
        "hero_i18n.json": HERO_I18N,
        "skill_i18n.json": SKILL_I18N
    }
    for fname, data in files.items():
        path = os.path.join(DICT_DIR, fname)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"Saved {fname} -> {path}")

if __name__ == "__main__":
    save_dicts()
